service: gonggangroom

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    COURSES_TABLE: Courses
    USERS_TABLE: Users
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:229116417118:table/${self:provider.environment.COURSES_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:229116417118:table/${self:provider.environment.USERS_TABLE}

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

custom:
  serverless-offline:
    httpPort: 8080
    noPrependStageInUrl: true

package:
  individually: true
